Updates for optical properties
ESCOMP/CARMA_base pull request #8
Opened 2023-06-06 17:44 UTC by fvitt

Chuck's updates for optical properties

2023-06-15 21:48 UTC, cbardeen requested changes
Just remove cstate from getwetr and I am happy.

2023-06-15 21:48 UTC, cbardeen commented on wetr.F90
> +  subroutine getwetr(carma, igroup, rh, rdry, rwet, rhopdry, rhopwet, rc, h2o_mass, h2o_vp, temp, kappa, cstate, wgtpct)
Please remove cstate. It is not needed.

2023-06-20 14:09 UTC, fvitt commented on wetr.F90
> +  subroutine getwetr(carma, igroup, rh, rdry, rwet, rhopdry, rhopwet, rc, h2o_mass, h2o_vp, temp, kappa, cstate, wgtpct)
cstate has been removed

2023-06-20 14:59 UTC, tilmes approved these changes

2023-06-20 15:44 UTC, cbardeen approved these changes

2023-06-20 19:04 UTC, merged